---
activity_array : ["Total population","Public supply","Domestic","Industrial","Total Thermoelectric Power","Fossil-fuel thermoelectric power","Geothermal thermoelectric power","Nuclear thermoelectric power","Thermoelectric power (once-through cooling)","Thermoelectric power (closed-loop cooling)","Mining","Livestock","Livestock (stock)","Livestock (animal specialties)","Aquaculture","Irrigation, total","Irrigation, crop","Irrigation, golf courses","Hydroelectric power","Wastewater treatment"]
surface_array : ["groundwater","surface", "total"]
water_type_array : ["fresh", "saline"]
technosphere_flow_array : ["consumptive"]
waste_flow_array : ["wastewater", "loss"]
usgs_url: 
  base_url: " https://waterdata.usgs.gov/"
  state_abrevation :  ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS","KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC","ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
  nwis: "/nwis/water_use?"
  params:
    format: "format="
    format_value: "rdb&rdb"
    compression: "_compression="
    compression_value: "value"
    area: "&wu_area="
    area_value: "County"
    year: "&wu_year="
    year_value: [2010, 2015] 
    county: "&wu_county="
    county_value: "ALL"
    category: "&wu_category="
    category_value: "ALL"