---
state_abrevation : ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS","KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC","ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
year : [2010, 2015] 
usgs_url_part_1: " https://waterdata.usgs.gov/"
usgs_url_part_2: "/nwis/water_use?format=rdb&rdb_compression=value&wu_area=County&wu_year="
usgs_url_part_3: "&wu_county=ALL&wu_category=ALL"
activity_array : ["Total population","Public supply","Domestic","Industrial","Total Thermoelectric Power","Fossil-fuel thermoelectric power","Geothermal thermoelectric power","Nuclear thermoelectric power","Thermoelectric power (once-through cooling)","Thermoelectric power (closed-loop cooling)","Mining","Livestock","Livestock (stock)","Livestock (animal specialties)","Aquaculture","Irrigation, total","Irrigation, crop","Irrigation, golf courses","Hydroelectric power","Wastewater treatment"]
surface_array : ["groundwater","surface", "total"]
water_type_array : ["fresh", "saline"]
technosphere_flow_array : ["consumptive"]
waste_flow_array : ["wastewater", "loss"]